_wandb:
    value:
        cli_version: 0.23.0
        e:
            3p9i2e4z5fkg7u9ppu1t0ox8nnhv9csf:
                codePath: atl_model_training/cleaned_for_comp/original_scripts/train_count_models.py
                codePathLocal: atl_model_training/cleaned_for_comp/original_scripts/train_count_models.py
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "33636024320"
                        used: "18793668608"
                email: joshuadariuspina@gmail.com
                executable: /workspaces/campus-burglary-risk-prediction/dsci_env/bin/python
                git:
                    commit: 3e783a43be57be51db1fdb4dec794b3190ff6ec5
                    remote: https://github.com/gsu-ds/campus-burglary-risk-prediction.git
                host: codespaces-398714
                memory:
                    total: "8330579968"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.39
                program: /workspaces/campus-burglary-risk-prediction/atl_model_training/cleaned_for_comp/original_scripts/train_count_models.py
                python: CPython 3.12.1
                root: /workspaces/campus-burglary-risk-prediction
                startedAt: "2025-12-04T17:45:55.387859Z"
                writerId: 3p9i2e4z5fkg7u9ppu1t0ox8nnhv9csf
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 5
                - 6
                - 7
                - 8
                - 53
                - 105
            "2":
                - 5
                - 6
                - 7
                - 8
                - 53
                - 105
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.1
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
baselines:
    value:
        - naive_24h
        - naive_168h
cutoff:
    value: "2024-01-01 00:00:00"
dataset:
    value: data/processed/apd/npu_dense_panel.parquet
models:
    value:
        - xgboost_poisson
        - lightgbm_poisson
        - catboost_poisson
        - zip
        - prophet_hourly_total
