_wandb:
    value:
        cli_version: 0.23.0
        e:
            qal869gu823ek23avf7vzw71lqdo6ghi:
                codePath: models/multi_models.py
                codePathLocal: models/multi_models.py
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "33636024320"
                        used: "18633347072"
                email: joshuadariuspina@gmail.com
                executable: /workspaces/campus-burglary-risk-prediction/dsci_env/bin/python
                git:
                    commit: 24becaebaa314f356343932b9e1d43e6d90d5ab2
                    remote: https://github.com/gsu-ds/campus-burglary-risk-prediction.git
                host: codespaces-398714
                memory:
                    total: "8330579968"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.39
                program: /workspaces/campus-burglary-risk-prediction/models/multi_models.py
                python: CPython 3.12.1
                root: /workspaces/campus-burglary-risk-prediction
                startedAt: "2025-12-02T18:49:05.912765Z"
                writerId: qal869gu823ek23avf7vzw71lqdo6ghi
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 5
                - 6
                - 7
                - 53
                - 105
            "2":
                - 5
                - 6
                - 7
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.1
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
dataset:
    value: npu_dense_panel
model:
    value: LinearRegression
