_wandb:
    value:
        cli_version: 0.23.0
        e:
            iudlof1anifby67m1bkyhd42wpob0g8h:
                codePath: /workspaces/campus-burglary-risk-prediction/notebooks/03_model.ipynb
                codePathLocal: 03_model.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "33636024320"
                        used: "17187528704"
                email: joshuadariuspina@gmail.com
                executable: /workspaces/campus-burglary-risk-prediction/dsci_env/bin/python
                git:
                    commit: d1f1d64f2f7acc197d9a3e161de55540929def3f
                    remote: https://github.com/gsu-ds/campus-burglary-risk-prediction.git
                host: codespaces-398714
                memory:
                    total: "8330579968"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.39
                program: /workspaces/campus-burglary-risk-prediction/notebooks/03_model.ipynb
                python: CPython 3.12.1
                root: /workspaces/campus-burglary-risk-prediction/reports/test_results/wandb
                startedAt: "2025-12-02T10:33:12.381341Z"
                writerId: iudlof1anifby67m1bkyhd42wpob0g8h
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 5
                - 6
                - 7
                - 53
                - 105
            "2":
                - 5
                - 6
                - 7
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.1
            "5": 0.23.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
features:
    value:
        - grid_density_7d
        - npu_crime_avg_30d
        - temp_f
        - is_raining
        - is_hot
        - is_cold
        - is_daylight
        - is_weekend
        - is_holiday
        - day_number
        - month
        - year
        - hour_sin
        - hour_cos
        - campus_distance_m
        - location_type_count
        - dow_Monday
        - dow_Saturday
        - dow_Sunday
        - dow_Thursday
        - dow_Tuesday
        - dow_Wednesday
group:
    value: rolling_cv
model:
    value: RandomForest
